

export enum MENU_TYPE {
    INIT = '1',
    DRAW_TRIANGLE = '2',
    RENDER_CUBE = '3',
    MULTI_OBJECTS = '4',
    MULTI_OBJECTS_BUFFERS = '4-1',
    MULTI_OBJECTS_BUFFERS_WITH_OFFSET = '4-2',
    MULTI_OBJECTS_DYNAMIC_OFFSET = '4-3',
    MULTI_OBJECTS_INSTANCE = '4-4',
    TEXTURE = '5',
    IMAGE_TEXTURE = '5-1',
    CANVAS_TEXTURE = '5-2',
    VIDEO_TEXTURE = '5-3',
}